export type Cycle20Target={domain:string;url:string;title:string;countryCode:string};

export const CYCLE20_TARGETS:Cycle20Target[]=[
  {domain:'planetretro.ie',url:'https://planetretro.ie',title:'Planet Retro',countryCode:'IE'},
  {domain:'luxurytoys.gr',url:'https://www.luxurytoys.gr/el',title:'Luxury Toys',countryCode:'GR'},
  {domain:'erikshjalpen.se',url:'https://erikshjalpen.se/en',title:'Erikshjälpen Second Hand',countryCode:'SE'},
  {domain:'humana.lt',url:'https://www.humana.lt',title:'Humana Lithuania',countryCode:'LT'},
  {domain:'leglantier.be',url:'https://www.leglantier.be/ressourcerie-folfouille.php',title:"La Fol'Fouille",countryCode:'BE'},
  {domain:'rebelshop.fi',url:'https://rebelshop.fi',title:'Rebel',countryCode:'FI'},
  {domain:'vaentupa.fi',url:'https://vaentupa.fi/tyollistaminen/retrokeidas',title:'Retrokeidas',countryCode:'FI'},
  {domain:'bjorkafrihet.se',url:'https://bjorkafrihet.se',title:'Björkåfrihet',countryCode:'SE'},
  {domain:'cetorisecondhand.fi',url:'https://www.cetorisecondhand.fi',title:'Cetori Second Hand',countryCode:'FI'},
  {domain:'danmission.dk',url:'https://danmission.dk',title:'Danmission Genbrug',countryCode:'DK'},
  {domain:'dorcas.nl',url:'https://dorcas.nl/kringloopwinkels',title:'Dorcas Kringloopwinkels',countryCode:'NL'},
  {domain:'faktory.ee',url:'https://faktory.ee',title:'Faktory taaskasutuspood',countryCode:'EE'},
  {domain:'fashionplanet.bg',url:'https://www.fashionplanet.bg',title:'Fashion Planet',countryCode:'BG'},
  {domain:'gladsaxe.drk.dk',url:'https://gladsaxe.drk.dk',title:'Dansk Røde Kors Gladsaxe',countryCode:'DK'},
  {domain:'humanae.ee',url:'https://humanae.ee',title:'Humana Estonia',countryCode:'EE'},
  {domain:'kfumgoteborg.se',url:'https://kfumgoteborg.se/secondhand.html',title:'KFUM Second Hand',countryCode:'SE'},
  {domain:'kringloopwinkelgoedengebruikt.nl',url:'https://kringloopwinkelgoedengebruikt.nl',title:'Goed & Gebruikt',countryCode:'NL'},
  {domain:'magia.bg',url:'https://magia.bg',title:'Magia',countryCode:'BG'},
  {domain:'minioplaneten.se',url:'https://minioplaneten.se',title:'Mini & Planeten',countryCode:'SE'},
  {domain:'natrahembygd.se',url:'https://natrahembygd.se/loppa.html',title:'Hembygdsgården Second Hand',countryCode:'SE'},
  {domain:'nbcgottne.se',url:'https://www.nbcgottne.se',title:'NBC Second Hand',countryCode:'SE'},
  {domain:'osthjalpen.se',url:'https://www.osthjalpen.se',title:'Östhjälpens Second Hand',countryCode:'SE'},
  {domain:'oxfambelgie.be',url:'https://oxfambelgie.be',title:'Oxfam België',countryCode:'BE'},
  {domain:'oxfammagasinsdumonde.be',url:'https://oxfammagasinsdumonde.be',title:'Oxfam Magasins du Monde',countryCode:'BE'},
  {domain:'pgterneuzen.nl',url:'https://www.pgterneuzen.nl/de_ontmoetkring',title:'OntmoetKRing',countryCode:'NL'},
  {domain:'pmu.se',url:'https://pmu.se/secondhand',title:'PMU Second Hand',countryCode:'SE'},
  {domain:'rezke.sk',url:'https://rezke.sk',title:'REZKE',countryCode:'SK'},
  {domain:'rodakorset.se',url:'https://www.rodakorset.se',title:'Röda Korset Second Hand',countryCode:'SE'},
  {domain:'saronsecondhand.se',url:'https://saronsecondhand.se',title:'Saron Second Hand',countryCode:'SE'},
  {domain:'secondfirst.se',url:'https://secondfirst.se/sv',title:'Second First',countryCode:'SE'},
  {domain:'textilehouse.sk',url:'https://textilehouse.sk',title:'Textile House',countryCode:'SK'},
  {domain:'uff.fi',url:'https://uff.fi',title:'UFF Finland',countryCode:'FI'},
  {domain:'uuskasutus.ee',url:'https://uuskasutus.ee',title:'Uuskasutuskeskus',countryCode:'EE'},
  {domain:'vestir.se',url:'https://vestir.se',title:'Vestir Second Hand',countryCode:'SE'},
  {domain:'humana-portugal.org',url:'https://www.humana-portugal.org',title:'Humana Portugal',countryCode:'PT'},
  {domain:'kirbukastallinnas.ee',url:'https://kirbukastallinnas.ee',title:'Kirbukas Tallinnas',countryCode:'EE'},
  {domain:'ropalavada.gr',url:'https://www.ropalavada.gr',title:'Ropa Lavada',countryCode:'GR'},
  {domain:'back2life.sk',url:'https://www.back2life.sk',title:'Back2Life',countryCode:'SK'},
  {domain:'remar.pt',url:'https://remar.pt',title:'Loja Solidária Remar',countryCode:'PT'},
  {domain:'scandinavianretrodesign.se',url:'https://scandinavianretrodesign.se/sv',title:'Scandinavian Retro Design',countryCode:'SE'},
  {domain:'vadelmatarha.fi',url:'https://www.vadelmatarha.fi',title:'Vadelmatarha',countryCode:'FI'},
  {domain:'yesterdaysbread.gr',url:'https://yesterdaysbread.gr',title:"Yesterday's Bread and Sons",countryCode:'GR'},
  {domain:'90scloset-skg.com',url:'https://90scloset-skg.com',title:'90s Closet',countryCode:'GR'},
  {domain:'associacaoreto.pt',url:'https://www.associacaoreto.pt',title:'Associação Reto',countryCode:'PT'},
  {domain:'larimarwebshop.hu',url:'http://www.larimarwebshop.hu',title:'Larimar Használtruha',countryCode:'HU'},
  {domain:'maniastores.bg',url:'https://maniastores.bg',title:'Mania Stores',countryCode:'BG'},
  {domain:'megakirbuhall.ee',url:'https://megakirbuhall.ee',title:'Mega Kirbuhall',countryCode:'EE'},
  {domain:'placeboshop.eu',url:'http://placeboshop.eu',title:'Placebo Shop',countryCode:'BG'},
  {domain:'retail.ncbi.ie',url:'https://www.retail.ncbi.ie',title:'NCBI Charity Shop',countryCode:'IE'},
  {domain:'roedekors.dk',url:'https://www.roedekors.dk',title:'Dansk Røde Kors Genbrug',countryCode:'DK'},
] as const;

if(CYCLE20_TARGETS.length!==50)throw new Error(`CYCLE20_TARGET_COUNT_${CYCLE20_TARGETS.length}`);
if(new Set(CYCLE20_TARGETS.map(target=>target.domain)).size!==50)throw new Error('CYCLE20_TARGET_DOMAIN_DUPLICATE');
