import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Camera, CheckCircle2, FileSearch, Fingerprint, Loader2, LockKeyhole, ScanEye, ShieldCheck } from "lucide-react";

function DecisionBadge({ value }: { value: string }) {
  const tone = value === "VERIFIED" || value === "VALIDATED" || value === "ACREDITED" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : value === "CONTRADICTED" || value === "BLOCKED" ? "border-red-200 bg-red-50 text-red-700" : value === "SUPPORTED" || value === "READY_FOR_REVIEW" ? "border-amber-200 bg-amber-50 text-amber-700" : "border-stone-200 bg-stone-100 text-stone-600";
  return <Badge variant="outline" className={`rounded-full border px-2 py-0.5 text-[10px] font-bold tracking-[0.12em] ${tone}`}>{value.replaceAll("_", " ")}</Badge>;
}

function Metric({ label, value, caption, icon: Icon }: { label: string; value: number; caption: string; icon: typeof Camera }) {
  return <Card className="border-stone-200 bg-white shadow-[0_12px_40px_-28px_rgba(33,29,24,0.35)]"><CardContent className="flex items-start justify-between p-5"><div><p className="text-[10px] font-bold tracking-[0.18em] text-stone-500">{label}</p><p className="mt-2 font-serif text-3xl text-stone-900">{value}</p><p className="mt-1 text-xs text-stone-500">{caption}</p></div><span className="rounded-xl bg-stone-900 p-2.5 text-stone-50"><Icon className="h-4 w-4" /></span></CardContent></Card>;
}

export default function VisualForensics() {
  const overview = trpc.workstream.visualOverview.useQuery(undefined, { refetchInterval: 10_000 });
  if (overview.isLoading) return <div className="flex min-h-96 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-stone-500" /></div>;
  if (overview.error) return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">{overview.error.message}</div>;
  const data = overview.data!;
  const validated = data.summaries.filter(summary => summary.manifest?.manifestStatus === "VALIDATED").length;
  const verifiedDecisions = data.decisions.filter(decision => decision.decision === "VERIFIED").length;

  return <div className="mx-auto max-w-[1540px] space-y-7 pb-10">
    <header className="relative overflow-hidden rounded-3xl border border-stone-200 bg-stone-950 px-6 py-7 text-stone-50 shadow-[0_24px_70px_-36px_rgba(16,14,10,0.78)] sm:px-8">
      <div className="absolute -right-16 -top-24 h-56 w-56 rounded-full border border-[#c6a15b]/35" /><div className="absolute -right-7 -top-14 h-40 w-40 rounded-full border border-[#c6a15b]/25" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold tracking-[0.26em] text-[#d9bc7a]">READY LIKE FREDDY · VISOR FORENSE</p><h1 className="mt-3 font-serif text-3xl leading-tight sm:text-4xl">Evidencia visual por pieza, no una galería.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-stone-300">Cuatro vistas estándar, cinco o seis macros canónicas y decisiones trazables. Cada conclusión conserva su límite probatorio.</p></div><div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs text-stone-300"><p className="font-bold tracking-[0.15em] text-[#d9bc7a]">FAIL-CLOSED</p><p className="mt-1">Sin derechos, hash o custodia: sin ingreso.</p></div></div>
    </header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="PIEZAS FÍSICAS" value={data.summaries.length} caption="registros reales" icon={Fingerprint} /><Metric label="ASSETS ACREDITADOS" value={data.accreditedAssetCount} caption="visibles en el visor" icon={Camera} /><Metric label="MANIFIESTOS VALIDADOS" value={validated} caption="4 + 5/6 completos" icon={CheckCircle2} /><Metric label="DECISIONES VERIFIED" value={verifiedDecisions} caption="con revisión física" icon={ShieldCheck} /></div>
    {(data.pendingAssetCount > 0 || data.rejectedAssetCount > 0) && <div className="rounded-2xl border border-amber-200 bg-amber-50 px-5 py-3 text-sm text-amber-900">Cuarentena de derechos: {data.pendingAssetCount} pendientes y {data.rejectedAssetCount} rechazados. Estos assets no aparecen como acreditados ni habilitan un manifiesto.</div>}
    {data.summaries.length === 0 ? <Card className="border-[#d9bc7a]/60 bg-[#fffbef]"><CardContent className="flex flex-col gap-4 p-6 md:flex-row md:items-center"><span className="rounded-2xl bg-stone-900 p-3 text-white"><LockKeyhole className="h-5 w-5" /></span><div><p className="font-serif text-2xl text-stone-900">No hay piezas ni imágenes ingresadas.</p><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-600">Este es el estado real del corpus visual: cero assets. El visor está listo para recibir solo un manifiesto de pieza física con derechos, custodia, hash y roles completos; no muestra imágenes de terceros ni construye una certeza sintética.</p></div></CardContent></Card> : <Card className="border-stone-200"><CardHeader className="border-b border-stone-100"><CardTitle className="font-serif text-2xl">Piezas documentadas</CardTitle><CardDescription>La identidad, autenticidad y conservación se muestran por campo y no se fusionan en una afirmación genérica.</CardDescription></CardHeader><CardContent className="p-0"><ScrollArea className="h-[500px]"><div className="divide-y divide-stone-100">{data.summaries.map(summary => <div key={summary.piece.id} className="grid gap-4 p-5 lg:grid-cols-[1.1fr_1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-sm font-semibold text-stone-700">{summary.piece.pieceRef}</p><DecisionBadge value={summary.piece.status} /></div><p className="mt-2 text-xs text-stone-500">Variante: {summary.piece.canonicalVariantRef}</p><p className="mt-1 text-xs text-stone-500">{summary.assetCount} assets acreditados · {summary.quarantinedAssetCount} en cuarentena · {summary.observationCount} observaciones</p></div><div className="flex flex-wrap content-start gap-2">{summary.decisions.length ? summary.decisions.map(decision => <span key={decision.id} className="inline-flex items-center gap-2 rounded-lg border border-stone-200 bg-stone-50 px-2 py-1 text-[11px] text-stone-700"><b>{decision.field}</b><DecisionBadge value={decision.decision} /></span>) : <span className="text-xs text-stone-400">Sin decisiones forenses</span>}</div><div className="justify-self-start lg:justify-self-end">{summary.manifest ? <DecisionBadge value={summary.manifest.manifestStatus} /> : <DecisionBadge value="INCOMPLETE" />}</div></div>)}</div></ScrollArea></CardContent></Card>}
    <div className="grid gap-6 xl:grid-cols-2"><Card className="border-stone-200"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-2xl"><ScanEye className="h-5 w-5 text-[#9b7639]" /> Paquete canónico</CardTitle><CardDescription>Roles que no se repiten ni se sustituyen entre sí.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><ProtocolRow label="4 vistas estándar" text="Primaria, reverso, perfil A y perfil B." /><ProtocolRow label="5 macros base" text="Marca, reglamentaria, identificador, construcción y firma." /><ProtocolRow label="1 macro condicional" text="Condición, desgaste o intervención cuando exista." /><ProtocolRow label="Hash y derechos" text="Cada archivo exige SHA-256, custodia y autorización." /></CardContent></Card><Card className="border-stone-200"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-2xl"><FileSearch className="h-5 w-5 text-[#9b7639]" /> Detalles discriminantes</CardTitle><CardDescription>El visor separa observación, evidencia y decisión.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm leading-6 text-stone-600"><p>Evalúa etiquetas, corona de llorer, costuras, piqué o tricot, botons, ferratges, mesures, composició, origen, coherència temporal i condició.</p><div className="flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-amber-900"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><p>Fotos i text de proveïdor poden aportar suport o contradicció, però no substitueixen el manifest complet ni la revisió humana de la peça física.</p></div></CardContent></Card></div>
  </div>;
}

function ProtocolRow({ label, text }: { label: string; text: string }) { return <div className="rounded-xl border border-stone-200 bg-stone-50 p-3"><p className="text-sm font-semibold text-stone-800">{label}</p><p className="mt-1 text-xs leading-5 text-stone-500">{text}</p></div>; }
